### ISSUE TITLE
`composer` should be executed by the user with same uid:gid as owner of composer.json

### ISSUE THREAD

**Issue by zaporylie** [php-actions/composer#31] opened 2020-12-08 16:37 UTC
I've experienced [this issue](https://github.com/actions/checkout/issues/273) by running following 2-steps-job on the self-hosted runner:

```
 steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v4
```

I've managed to debug this issue and it is happening because `actions/checkout` cannot reset the state of the workdir, which is caused by `php-actions/composer` running as root:root. However,`actions/checkout` is being run by the same user who "owns" the self-hosted runner (non-root user).

**Comment by g105b** [comment] 2020-12-08 17:06
Thanks for reporting this. I will look into creating a test case in https://github.com/php-actions/example-composer so we can replicate the issue. Any help to reproduce it will be appreciated.

**Comment by eugene-manuilov** [comment] 2020-12-16 21:22
@g105b any progress on this issue?

**Comment by g105b** [comment] 2020-12-23 09:56
I've just made a release of v5 to this repository, so I can take a proper look at this. The issue is caused by using a self-hosted runner (I missed that previously).

Please take a look here:

https://github.com/php-actions/composer/blob/master/composer-action.bash#L135-L143

It's possible to use the `--user` flag on Docker to run as a specific user ID (https://docs.docker.com/engine/reference/run/#user), but I'm unable to test this as I don't have any self-hosted runners.

I'm happy to do some testing with you to help solve this issue. First we will need to find what user to run as, then we can test this on a separate branch. How can we figure out the correct user to run as?

**Comment by g105b** [comment] 2021-01-29 09:41
I'm closing this issue as I haven't had any further reports since the v5 release. Please feel free to re-open if this issue is still affecting you, and I'll pick it back up and dig a little deeper.

**Closed by g105b** 2021-01-29 09:41 UTC

**Comment by constantinultius** [comment] 2021-04-20 19:01
I confirm it still happens on self-hosted runner with @v5.  It installs packages under "/vendor" folder with owner "root:root" and not runner user.   It works on first run but then fails on subsequent, when runner tries to clean up working directory. Because "root" files can't be deleted.

```
      - name: Install PHP packages
        uses: php-actions/composer@v5
        with:
          php_version: 7.3
          args: --profile --ignore-platform-reqs --no-cache
```

**Comment by swichers** [comment] 2022-04-26 08:32
Still an issue on v6.

**Comment by g105b** [comment] 2022-04-26 11:22
Can anyone help me understand how to detect the user on a self-hosted runner? I'm not familiar with self-hosted Actions. Any advice is appreciated, so I can create a test case in [example-composer](https://github.com/php-actions/example-composer)
