### ISSUE TITLE
cat output.log no such file

### ISSUE THREAD

**Issue by markkimsal** [php-actions/composer#52] opened 2021-04-05 15:50 UTC
```
            - name: Install Dependencies
              uses: php-actions/composer@v5
              with:
                  dev: yes
                  version: 1
                  php_version: 7.3
                  command: install
                  args: -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
```

The output just says
```
cat: /home/runner/work/accounts/accounts/output.log: No such file or directory
```
![image](https://user-images.githubusercontent.com/54099/113593891-f63a8d00-9604-11eb-8555-1c46097631ff.png)

**Comment by g105b** [comment] 2021-04-06 13:44
Hello, thank you for your message. I have just hit this myself and have found out what the issue is: recently Github bumped the default OS from Ubuntu 18.04 to Ubuntu 20.04. I'm not sure why this has caused an issue, but it's certainly too much of a coincidence to ignore.

My plan is to hardcode the reference to the previously working Ubuntu 18.04, make a patch to the v5 release, then move on to investigate what incompatibility there is caused by the newer OS.

**Comment by g105b** [comment] 2021-04-06 14:02
@markkimsal please see https://github.com/php-actions/composer/issues/53 where there has been a duplicated issue. There is more discussion happening in that thread in case you wanted to follow along.

**Comment by g105b** [comment] 2021-04-07 12:24
It seems that Github have fixed this issue. I've reached out to support to see if there is anything that could have been done differently to prevent this issue, but for now it seems like you don't need to make any adjustments to anything to continue using the action.

I'm going to close this issue now but please open it again if you have any further problems.

**Closed by g105b** 2021-04-07 12:24 UTC
